notifiers:
  - name: Telegram
    type: telegram
    uid: telegram_lido
    # either
    # org_id: 2
    is_default: false
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    # See `Supported Settings` section for settings supported for each
    # alert notification type.
    settings:
      uploadImage: true
      chatid: $TELEGRAM_CHAT_ID
    # Secure settings that will be encrypted in the database (supported since Grafana v7.2).
    # See `Supported Settings` section for secure settings supported for each notifier.
    secure_settings:
      bottoken: $TELEGRAM_BOTTOKEN
  - name: Telegram no reminder no recover
    type: telegram
    uid: telegram_lido_no_reminder_no_recover
    # either
    # org_id: 2
    is_default: false
    send_reminder: false
    frequency: 1h
    disable_resolve_message: true
    # See `Supported Settings` section for settings supported for each
    # alert notification type.
    settings:
      uploadImage: true
      chatid: $TELEGRAM_CHAT_ID
    # Secure settings that will be encrypted in the database (supported since Grafana v7.2).
    # See `Supported Settings` section for secure settings supported for each notifier.
    secure_settings:
      bottoken: $TELEGRAM_BOTTOKEN